from datetime import datetime

from fastapi import HTTPException
from psycopg import Connection


def ensure_ore_schema(conn: Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS ore_progetto (
                id_ore INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_user_id INTEGER NOT NULL,
                data_lavoro TEXT NOT NULL,
                id_progetto INTEGER,
                nome_progetto_snapshot TEXT NOT NULL,
                ore REAL NOT NULL,
                note TEXT,
                created_at TEXT NOT NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS ore_progetto_mesi (
                owner_user_id INTEGER NOT NULL,
                mese TEXT NOT NULL,
                chiuso INTEGER NOT NULL DEFAULT 0,
                chiuso_at TEXT,
                PRIMARY KEY (owner_user_id, mese)
            )
            """
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_ore_progetto_owner_data ON ore_progetto(owner_user_id, data_lavoro)"
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_ore_progetto_owner_mese ON ore_progetto(owner_user_id, substr(data_lavoro,1,7))"
        )
    conn.commit()


def get_utente_corrente(conn: Connection, user_id: int) -> dict:
    with conn.cursor() as cur:
        cur.execute("SELECT id_utente, username FROM utenti WHERE id_utente = %s LIMIT 1", (user_id,))
        row = cur.fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="Utente non trovato")
    return {"id_utente": int(row[0]), "username": str(row[1] or "")}


def list_progetti_attivi(conn: Connection, *, user_ruolo: str, user_id: int) -> list[dict]:
    sql = """
        SELECT id_progetto, nome_progetto
        FROM progetti
        WHERE attivo = 1
          AND (archiviato = 0 OR archiviato IS NULL)
    """
    params = []
    if user_ruolo != "ADMIN":
        sql += " AND (owner_user_id = %s OR owner_user_id IS NULL)"
        params.append(user_id)
    sql += " ORDER BY COALESCE(ordine_manuale, id_progetto), id_progetto"

    with conn.cursor() as cur:
        cur.execute(sql, tuple(params) if params else None)
        rows = cur.fetchall()
    return [{"id_progetto": int(r[0]), "nome_progetto": str(r[1] or "")} for r in rows]


def get_mese_chiuso(conn: Connection, *, user_id: int, mese: str) -> bool:
    ensure_ore_schema(conn)
    with conn.cursor() as cur:
        cur.execute(
            "SELECT chiuso FROM ore_progetto_mesi WHERE owner_user_id = %s AND mese = %s",
            (user_id, mese),
        )
        row = cur.fetchone()
    return bool(row[0]) if row else False


def chiudi_mese(conn: Connection, *, user_id: int, mese: str) -> dict:
    ensure_ore_schema(conn)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO ore_progetto_mesi(owner_user_id, mese, chiuso, chiuso_at)
            VALUES (%s, %s, 1, %s)
            ON CONFLICT(owner_user_id, mese)
            DO UPDATE SET chiuso = 1, chiuso_at = EXCLUDED.chiuso_at
            """,
            (user_id, mese, ts),
        )
    conn.commit()
    return {"ok": True, "mese": mese, "chiuso": True}


def riapri_mese(conn: Connection, *, user_id: int, mese: str) -> dict:
    ensure_ore_schema(conn)
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO ore_progetto_mesi(owner_user_id, mese, chiuso, chiuso_at)
            VALUES (%s, %s, 0, NULL)
            ON CONFLICT(owner_user_id, mese)
            DO UPDATE SET chiuso = 0, chiuso_at = NULL
            """,
            (user_id, mese),
        )
    conn.commit()
    return {"ok": True, "mese": mese, "chiuso": False}


def list_righe_mese(conn: Connection, *, user_id: int, mese: str) -> list[dict]:
    ensure_ore_schema(conn)
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id_ore, data_lavoro, id_progetto, nome_progetto_snapshot, ore, note, created_at
            FROM ore_progetto
            WHERE owner_user_id = %s
              AND substr(data_lavoro, 1, 7) = %s
            ORDER BY data_lavoro ASC, id_ore ASC
            """,
            (user_id, mese),
        )
        rows = cur.fetchall()
    return [
        {
            "id_ore": int(r[0]),
            "data_lavoro": str(r[1] or ""),
            "id_progetto": r[2],
            "nome_progetto_snapshot": str(r[3] or ""),
            "ore": float(r[4] or 0),
            "note": str(r[5] or ""),
            "created_at": str(r[6] or ""),
        }
        for r in rows
    ]


def get_totale_mese(conn: Connection, *, user_id: int, mese: str) -> dict:
    ensure_ore_schema(conn)
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT COALESCE(SUM(ore), 0)
            FROM ore_progetto
            WHERE owner_user_id = %s
              AND substr(data_lavoro, 1, 7) = %s
            """,
            (user_id, mese),
        )
        row = cur.fetchone()
    return {"mese": mese, "totale": float(row[0] or 0)}


def inserisci_riga(
    conn: Connection,
    *,
    user_id: int,
    data_lavoro: str,
    ore: float,
    nome_progetto_snapshot: str,
    id_progetto: int | None,
    note: str,
) -> int:
    ensure_ore_schema(conn)
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO ore_progetto(owner_user_id, data_lavoro, id_progetto, nome_progetto_snapshot, ore, note, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id_ore
            """,
            (
                user_id,
                data_lavoro,
                id_progetto,
                nome_progetto_snapshot,
                float(ore),
                note,
                datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            ),
        )
        new_id = int(cur.fetchone()[0])
    conn.commit()
    return new_id


def elimina_riga(conn: Connection, *, user_id: int, id_ore: int) -> dict:
    ensure_ore_schema(conn)
    with conn.cursor() as cur:
        cur.execute(
            "DELETE FROM ore_progetto WHERE id_ore = %s AND owner_user_id = %s",
            (id_ore, user_id),
        )
    conn.commit()
    return {"ok": True, "id_ore": id_ore}
