import psycopg
from datetime import datetime
import os
import shutil
import uuid
import hashlib
import hmac
import secrets
from config import get_attachments_dir, get_postgres_dsn, get_project_root

def _adapt_params(query: str) -> str:
    # Consente di mantenere i placeholder "?" legacy anche con psycopg (%s).
    return query.replace("?", "%s")


class CompatCursor:
    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        if params is None:
            return self._cursor.execute(_adapt_params(query))
        return self._cursor.execute(_adapt_params(query), params)

    def executemany(self, query, params_seq):
        return self._cursor.executemany(_adapt_params(query), params_seq)

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __iter__(self):
        return iter(self._cursor)

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class CompatConnection:
    def __init__(self, conn):
        self._conn = conn

    def cursor(self):
        return CompatCursor(self._conn.cursor())

    def commit(self):
        return self._conn.commit()

    def rollback(self):
        return self._conn.rollback()

    def close(self):
        return self._conn.close()

    def __getattr__(self, name):
        return getattr(self._conn, name)


def connetti():
    return CompatConnection(psycopg.connect(get_postgres_dsn()))


_CURRENT_USER_ID = None
_CURRENT_USER_ROLE = None

PERM_APP_GESTIONE_OPEN = "APP_GESTIONE_OPEN"
PERM_APP_AS400_OPEN = "APP_AS400_OPEN"


def set_current_user(user: dict | None):
    global _CURRENT_USER_ID, _CURRENT_USER_ROLE
    if not user:
        _CURRENT_USER_ID = None
        _CURRENT_USER_ROLE = None
        return
    _CURRENT_USER_ID = user.get("id_utente")
    _CURRENT_USER_ROLE = (user.get("ruolo") or "").upper()


def clear_current_user():
    set_current_user(None)


def _is_admin() -> bool:
    return _CURRENT_USER_ROLE == "ADMIN"


def _current_user_id():
    return _CURRENT_USER_ID


def owner_filter_sql(alias: str = "", column: str = "owner_user_id", leading_and: bool = True):
    """
    Ritorna clausola SQL + params per filtrare per utente corrente.
    - ADMIN o utente non impostato: nessun filtro.
    - Utente normale: filtro su <alias>.<column> = ?
    """
    uid = _current_user_id()
    if uid is None or _is_admin():
        return "", ()
    prefix = f"{alias}." if alias else ""
    head = " AND " if leading_and else ""
    return f"{head}{prefix}{column} = ?", (uid,)
# --------------------------------------------------------
# FUNZIONE DI SICUREZZA (AGGIUNGE COLONNE SE MANCANO)
# --------------------------------------------------------
def verifica_e_aggiorna_colonna(tabella, colonna, tipo_dati):
    """Controlla se una colonna c'Ã¨. Se manca, la aggiunge senza cancellare i dati."""
    conn = connetti()
    c = conn.cursor()
    try:
        c.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = %s
            """,
            (tabella, colonna),
        )
        if c.fetchone() is None:
            c.execute(f"ALTER TABLE {tabella} ADD COLUMN {colonna} {tipo_dati}")
            conn.commit()
    except Exception:
        pass # Se fallisce (es. tabella non esiste ancora) va avanti
    finally:
        conn.close()

# --------------------------------------------------------
# INIZIALIZZAZIONE (USA I TUOI NOMI ORIGINALI)
# --------------------------------------------------------
def inizializza_db():
    conn = connetti()
    c = conn.cursor()
    
    # 1. TABELLA PROGETTI (Con nome_progetto e id_stato)
    c.execute("""
        CREATE TABLE IF NOT EXISTS progetti (
            id_progetto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome_progetto TEXT NOT NULL,
            note TEXT,
            data_inserimento TEXT,
            ticket_interno VARCHAR(20),
            ticket_esterno VARCHAR(20),
            id_stato INTEGER DEFAULT 1,
            percentuale_avanzamento INTEGER DEFAULT 0,
            attivo INTEGER DEFAULT 1
        )
    """)

    # 2. TABELLA TASK (SINGOLARE)
    # Nota: Qui usiamo id_progetto per coerenza, e aggiungiamo id_risorsa
    c.execute("""
        CREATE TABLE IF NOT EXISTS task (
            id_task INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_progetto INTEGER, 
            titolo TEXT NOT NULL,
            data_inizio TEXT,
            data_fine TEXT,
            percentuale_avanzamento INTEGER DEFAULT 0,
            tipo_task INTEGER DEFAULT 1,
            id_stato INTEGER DEFAULT 1,
            completato INTEGER DEFAULT 0,
            id_risorsa INTEGER,
            id_ruolo INTEGER,
            data_inserimento TEXT,
            data_completato TEXT,
            ticket_interno VARCHAR(20),
            ticket_esterno VARCHAR(20),
            attivo INTEGER DEFAULT 1
        )
    """)

    # 3. TABELLA RISORSE
    c.execute("""
        CREATE TABLE IF NOT EXISTS risorse (
            id_risorsa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT,
            cognome TEXT,
            email TEXT,
            attivo INTEGER DEFAULT 1
        )
    """)

    # 4. TABELLA RUOLI
    c.execute("""
        CREATE TABLE IF NOT EXISTS ruoli (
            id_ruolo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome_ruolo TEXT,
            attivo INTEGER DEFAULT 1
        )
    """)

    # 5. TABELLA STATI (Per le dropdown)
    c.execute("""
        CREATE TABLE IF NOT EXISTS tab_stati (
            id_stato INTEGER PRIMARY KEY,
            nome_stato TEXT
        )
    """)

    # 6. TABELLA ALLEGATI TASK
    c.execute("""
        CREATE TABLE IF NOT EXISTS task_allegati (
            id_allegato INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_task INTEGER NOT NULL,
            nome_originale TEXT NOT NULL,
            nome_file_storage TEXT NOT NULL,
            percorso_relativo TEXT NOT NULL,
            data_inserimento TEXT,
            attivo INTEGER DEFAULT 1
        )
    """)

    # 7. TABELLA NOTE GIORNATA
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS note_giornata (
            id_nota INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data_nota TEXT NOT NULL,
            ora_nota TEXT,
            testo TEXT NOT NULL,
            id_progetto INTEGER,
            id_task INTEGER,
            attivo INTEGER DEFAULT 1
        )
        """
    )

    # 8. TABELLA UTENTI (autenticazione e ruoli)
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS utenti (
            id_utente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(80) NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            nome VARCHAR(120),
            cognome VARCHAR(120),
            email VARCHAR(180),
            ruolo VARCHAR(20) NOT NULL DEFAULT 'USER',
            attivo INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # 9. RBAC WEB (ruoli/permessi/applicazioni)
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS ruoli_app (
            id_ruolo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            codice VARCHAR(50) NOT NULL UNIQUE,
            descrizione VARCHAR(150)
        )
        """
    )
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS permessi (
            id_permesso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            codice VARCHAR(80) NOT NULL UNIQUE,
            descrizione VARCHAR(200)
        )
        """
    )
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS utenti_ruoli (
            id_utente INTEGER NOT NULL,
            id_ruolo INTEGER NOT NULL,
            PRIMARY KEY (id_utente, id_ruolo),
            FOREIGN KEY (id_utente) REFERENCES utenti(id_utente) ON DELETE CASCADE,
            FOREIGN KEY (id_ruolo) REFERENCES ruoli_app(id_ruolo) ON DELETE CASCADE
        )
        """
    )
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS ruoli_permessi (
            id_ruolo INTEGER NOT NULL,
            id_permesso INTEGER NOT NULL,
            PRIMARY KEY (id_ruolo, id_permesso),
            FOREIGN KEY (id_ruolo) REFERENCES ruoli_app(id_ruolo) ON DELETE CASCADE,
            FOREIGN KEY (id_permesso) REFERENCES permessi(id_permesso) ON DELETE CASCADE
        )
        """
    )
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS categorie_modulo (
            codice VARCHAR(5) PRIMARY KEY,
            descrizione VARCHAR(120) NOT NULL
        )
        """
    )

    c.execute(
        """
        CREATE TABLE IF NOT EXISTS applicazioni (
            id_app INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            codice VARCHAR(80) NOT NULL UNIQUE,
            nome VARCHAR(120) NOT NULL,
            route VARCHAR(120) NOT NULL,
            attiva BOOLEAN NOT NULL DEFAULT TRUE,
            descrizione VARCHAR(250),
            icona VARCHAR(80),
            categoria VARCHAR(5),
            ordine_menu INTEGER DEFAULT 1000,
            visibile_menu BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )
    c.execute("ALTER TABLE applicazioni ADD COLUMN IF NOT EXISTS descrizione VARCHAR(250)")
    c.execute("ALTER TABLE applicazioni ADD COLUMN IF NOT EXISTS icona VARCHAR(80)")
    c.execute("ALTER TABLE applicazioni ADD COLUMN IF NOT EXISTS categoria VARCHAR(80)")
    c.execute("UPDATE applicazioni SET categoria = LEFT(UPPER(TRIM(COALESCE(categoria, ''))), 5) WHERE categoria IS NOT NULL")
    c.execute("ALTER TABLE applicazioni ALTER COLUMN categoria TYPE VARCHAR(5)")
    c.execute("ALTER TABLE applicazioni ADD COLUMN IF NOT EXISTS ordine_menu INTEGER DEFAULT 1000")
    c.execute("ALTER TABLE applicazioni ADD COLUMN IF NOT EXISTS visibile_menu BOOLEAN DEFAULT TRUE")
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS applicazioni_permessi (
            id_app INTEGER NOT NULL,
            id_permesso INTEGER NOT NULL,
            PRIMARY KEY (id_app, id_permesso),
            FOREIGN KEY (id_app) REFERENCES applicazioni(id_app) ON DELETE CASCADE,
            FOREIGN KEY (id_permesso) REFERENCES permessi(id_permesso) ON DELETE CASCADE
        )
        """
    )

    c.execute(
        """
        CREATE TABLE IF NOT EXISTS utenti_applicazioni (
            id_utente INTEGER NOT NULL,
            id_app INTEGER NOT NULL,
            attivo BOOLEAN NOT NULL DEFAULT TRUE,
            PRIMARY KEY (id_utente, id_app),
            FOREIGN KEY (id_utente) REFERENCES utenti(id_utente) ON DELETE CASCADE,
            FOREIGN KEY (id_app) REFERENCES applicazioni(id_app) ON DELETE CASCADE
        )
        """
    )

    c.execute(
        """
        INSERT INTO tab_stati (id_stato, nome_stato) VALUES
            (1, 'Da fare'),
            (2, 'In corso'),
            (3, 'Completato')
        ON CONFLICT (id_stato) DO NOTHING
        """
    )

    # Seed ruoli
    c.execute(
        """
        INSERT INTO ruoli_app (codice, descrizione) VALUES
            ('ADMIN', 'Amministratore'),
            ('USER', 'Utente standard')
        ON CONFLICT (codice) DO NOTHING
        """
    )
    # Seed permessi
    c.execute(
        """
        INSERT INTO permessi (codice, descrizione) VALUES
            (%s, 'Accesso modulo Organizer Project'),
            (%s, 'Accesso modulo AS400')
        ON CONFLICT (codice) DO NOTHING
        """,
        (PERM_APP_GESTIONE_OPEN, PERM_APP_AS400_OPEN),
    )
    # Seed categorie modulo
    c.execute(
        """
        INSERT INTO categorie_modulo (codice, descrizione) VALUES
            ('UTILY', 'Utility interne'),
            ('ICT', 'Programmi uff.ICT')
        ON CONFLICT (codice)
        DO UPDATE SET
            descrizione = EXCLUDED.descrizione
        """
    )

    # Seed applicazioni menu
    c.execute(
        """
        INSERT INTO applicazioni (codice, nome, route, attiva, categoria) VALUES
            ('GESTIONE', 'Organizer Project', '/gestione', TRUE, 'UTILY'),
            ('AS400', 'AS400', '/as400', TRUE, 'UTILY'),
            ('ORE_PROGETTO', 'Ore Progetto', '/ore-progetto', TRUE, 'ICT')
        ON CONFLICT (codice)
        DO UPDATE SET
            nome = EXCLUDED.nome,
            route = EXCLUDED.route,
            attiva = EXCLUDED.attiva,
            categoria = COALESCE(applicazioni.categoria, EXCLUDED.categoria)
        """
    )
    c.execute(
        """
        INSERT INTO applicazioni (codice, nome, route, attiva, categoria) VALUES
            ('ADMIN_MENU', 'Administrator Menu', '/admin', TRUE, 'UTILY')
        ON CONFLICT (codice)
        DO UPDATE SET
            nome = EXCLUDED.nome,
            route = EXCLUDED.route,
            attiva = EXCLUDED.attiva,
            categoria = COALESCE(applicazioni.categoria, EXCLUDED.categoria)
        """
    )
    # Mappa ADMIN -> tutti i permessi
    c.execute(
        """
        INSERT INTO ruoli_permessi (id_ruolo, id_permesso)
        SELECT r.id_ruolo, p.id_permesso
        FROM ruoli_app r
        CROSS JOIN permessi p
        WHERE r.codice = 'ADMIN'
        ON CONFLICT (id_ruolo, id_permesso) DO NOTHING
        """
    )
    # Mappa USER -> solo gestione
    c.execute(
        """
        INSERT INTO ruoli_permessi (id_ruolo, id_permesso)
        SELECT r.id_ruolo, p.id_permesso
        FROM ruoli_app r
        JOIN permessi p ON p.codice = %s
        WHERE r.codice = 'USER'
        ON CONFLICT (id_ruolo, id_permesso) DO NOTHING
        """,
        (PERM_APP_GESTIONE_OPEN,),
    )
    # Mappa applicazioni -> permessi richiesti
    c.execute(
        """
        INSERT INTO applicazioni_permessi (id_app, id_permesso)
        SELECT a.id_app, p.id_permesso
        FROM applicazioni a
        JOIN permessi p ON p.codice = %s
        WHERE a.codice = 'GESTIONE'
        ON CONFLICT (id_app, id_permesso) DO NOTHING
        """,
        (PERM_APP_GESTIONE_OPEN,),
    )
    c.execute(
        """
        INSERT INTO applicazioni_permessi (id_app, id_permesso)
        SELECT a.id_app, p.id_permesso
        FROM applicazioni a
        JOIN permessi p ON p.codice = %s
        WHERE a.codice = 'AS400'
        ON CONFLICT (id_app, id_permesso) DO NOTHING
        """,
        (PERM_APP_AS400_OPEN,),
    )

    conn.commit()
    conn.close()

    # AGGIORNAMENTO SICURO: aggiunge i campi mancanti su DB vecchi.
    # UTENTI
    verifica_e_aggiorna_colonna("utenti", "nome", "VARCHAR(120)")
    verifica_e_aggiorna_colonna("utenti", "cognome", "VARCHAR(120)")
    verifica_e_aggiorna_colonna("utenti", "email", "VARCHAR(180)")

    # PROGETTI
    verifica_e_aggiorna_colonna("progetti", "id_resp1", "INTEGER")
    verifica_e_aggiorna_colonna("progetti", "id_ruolo_resp1", "INTEGER")
    verifica_e_aggiorna_colonna("progetti", "id_resp2", "INTEGER")
    verifica_e_aggiorna_colonna("progetti", "id_ruolo_resp2", "INTEGER")
    verifica_e_aggiorna_colonna("progetti", "data_inserimento", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "data_chiusura", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "completato", "INTEGER DEFAULT 0")
    verifica_e_aggiorna_colonna("progetti", "data_eliminazione", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "data1_checkpoint", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "data2_checkpoint", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "data3_checkpoint", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "ordine_manuale", "INTEGER")
    verifica_e_aggiorna_colonna("progetti", "archiviato", "INTEGER DEFAULT 0")
    verifica_e_aggiorna_colonna("progetti", "data_archiviazione", "TEXT")
    verifica_e_aggiorna_colonna("progetti", "owner_user_id", "INTEGER")
    verifica_e_aggiorna_colonna("progetti", "ticket_interno", "VARCHAR(20)")
    verifica_e_aggiorna_colonna("progetti", "ticket_esterno", "VARCHAR(20)")

    # TASK
    verifica_e_aggiorna_colonna("task", "data_inizio", "TEXT")
    verifica_e_aggiorna_colonna("task", "data_fine", "TEXT")
    verifica_e_aggiorna_colonna("task", "percentuale_avanzamento", "INTEGER DEFAULT 0")
    verifica_e_aggiorna_colonna("task", "tipo_task", "INTEGER DEFAULT 1")
    verifica_e_aggiorna_colonna("task", "id_stato", "INTEGER DEFAULT 1")
    verifica_e_aggiorna_colonna("task", "completato", "INTEGER DEFAULT 0")
    verifica_e_aggiorna_colonna("task", "id_risorsa", "INTEGER")
    verifica_e_aggiorna_colonna("task", "id_ruolo", "INTEGER")
    verifica_e_aggiorna_colonna("task", "data_inserimento", "TEXT")
    verifica_e_aggiorna_colonna("task", "data_completato", "TEXT")
    verifica_e_aggiorna_colonna("task", "data_eliminazione", "TEXT")
    verifica_e_aggiorna_colonna("task", "archiviato", "INTEGER DEFAULT 0")
    verifica_e_aggiorna_colonna("task", "data_archiviazione", "TEXT")
    verifica_e_aggiorna_colonna("task", "id_parent", "INTEGER")
    verifica_e_aggiorna_colonna("task", "owner_user_id", "INTEGER")
    verifica_e_aggiorna_colonna("task", "ticket_interno", "VARCHAR(20)")
    verifica_e_aggiorna_colonna("task", "ticket_esterno", "VARCHAR(20)")

    # ALLEGATI TASK
    verifica_e_aggiorna_colonna("task_allegati", "attivo", "INTEGER DEFAULT 1")
    verifica_e_aggiorna_colonna("task_allegati", "owner_user_id", "INTEGER")

    # NOTE GIORNATA
    verifica_e_aggiorna_colonna("note_giornata", "owner_user_id", "INTEGER")

# --------------------------------------------------------
# GESTIONE PROGETTI (Mapping Corretto: nome_progetto)
# --------------------------------------------------------
def aggiungi_progetto(nome, note, stato_id):
    conn = connetti()
    c = conn.cursor()
    owner_filter, owner_params = owner_filter_sql("p")
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    c.execute(
        f"""
        SELECT COALESCE(MAX(ordine_manuale), 0)
        FROM progetti
        WHERE attivo = 1 AND (archiviato = 0 OR archiviato IS NULL){owner_filter}
        """,
        (uid,) if owner_filter else None,
    )
    next_ordine = (c.fetchone()[0] or 0) + 1
    data_ins = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    c.execute(
        """
        INSERT INTO progetti (nome_progetto, note, data_inserimento, id_stato, attivo, ordine_manuale, owner_user_id, ticket_interno, ticket_esterno)
        VALUES (?, ?, ?, ?, 1, ?, ?, '', '')
        """,
        (nome, note, data_ins, stato_id, next_ordine, uid),
    )
    conn.commit()
    conn.close()


def riallinea_ordine_progetti():
    """
    Garantisce un ordine continuo (1..N) per i progetti attivi non archiviati.
    Utile per mantenere stabile lo spostamento su/giu'.
    """
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT id_progetto
        FROM progetti
        WHERE attivo = 1 AND (archiviato = 0 OR archiviato IS NULL)
        ORDER BY COALESCE(ordine_manuale, id_progetto) ASC, id_progetto ASC
        """
    )
    ids = [r[0] for r in c.fetchall()]
    for idx, id_progetto in enumerate(ids, start=1):
        c.execute(
            "UPDATE progetti SET ordine_manuale = ? WHERE id_progetto = ?",
            (idx, id_progetto),
        )
    conn.commit()
    conn.close()


def sposta_progetto(id_progetto, direzione):
    """
    Sposta il progetto di una posizione nell'ordine manuale.
    direzione: 'up' o 'down'
    """
    if direzione not in ("up", "down"):
        return False

    riallinea_ordine_progetti()
    conn = connetti()
    c = conn.cursor()

    try:
        c.execute(
            """
            SELECT ordine_manuale
            FROM progetti
            WHERE id_progetto = ?
              AND attivo = 1
              AND (archiviato = 0 OR archiviato IS NULL)
            """,
            (id_progetto,),
        )
        row = c.fetchone()
        if not row:
            conn.close()
            return False

        ordine_corrente = int(row[0] or 0)
        ordine_target = ordine_corrente - 1 if direzione == "up" else ordine_corrente + 1
        if ordine_target < 1:
            conn.close()
            return False

        c.execute(
            """
            SELECT id_progetto
            FROM progetti
            WHERE attivo = 1
              AND (archiviato = 0 OR archiviato IS NULL)
              AND ordine_manuale = ?
            """,
            (ordine_target,),
        )
        target_row = c.fetchone()
        if not target_row:
            conn.close()
            return False

        id_target = target_row[0]
        c.execute(
            "UPDATE progetti SET ordine_manuale = ? WHERE id_progetto = ?",
            (ordine_target, id_progetto),
        )
        c.execute(
            "UPDATE progetti SET ordine_manuale = ? WHERE id_progetto = ?",
            (ordine_corrente, id_target),
        )
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        print(f"Errore spostamento progetto: {e}")
        conn.rollback()
        conn.close()
        return False

def leggi_progetto_per_modifica(id_progetto):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    query = f"""
        SELECT 
            nome_progetto, 
            note, 
            id_stato, 
            percentuale_avanzamento,
            id_resp1, 
            id_ruolo_resp1, 
            id_resp2, 
            id_ruolo_resp2,
            data1_checkpoint,
            COALESCE(ticket_interno, '') AS ticket_interno,
            COALESCE(ticket_esterno, '') AS ticket_esterno
        FROM progetti 
        WHERE id_progetto = ?
    """
    query += owner_filter
    c.execute(query, (id_progetto,) if not owner_filter else (id_progetto, uid))
    row = c.fetchone()
    conn.close()
    return row

def leggi_progetti_attivi():
    inizializza_db() # Assicura che le colonne esistano
    riallinea_ordine_progetti()
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    # QUERY CORRETTA: Recupera nome_progetto e id_stato
    sql = f"""
        SELECT 
            id_progetto, 
            nome_progetto, 
            note, 
            id_stato, 
            percentuale_avanzamento,
            id_resp1, 
            id_ruolo_resp1, 
            id_resp2, 
            id_ruolo_resp2,
            data_chiusura,
            ordine_manuale
        FROM progetti 
        WHERE attivo = 1 
          AND (archiviato = 0 OR archiviato IS NULL)
          {owner_filter}
        ORDER BY ordine_manuale ASC, id_progetto ASC
    """
    c.execute(sql, (uid,) if owner_filter else None)
    items = c.fetchall()
    conn.close()
    return items

def toggle_chiusura_progetto(id_progetto, stato_attuale_chiuso):
    """
    Toggle semplice data chiusura progetto.
    - Se aperto -> imposta data_chiusura progetto e data_completato su tutti i task attivi.
    - Se chiuso -> azzera data_chiusura progetto e data_completato task attivi.
    """
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    if uid is not None and not _is_admin():
        c.execute("SELECT 1 FROM progetti WHERE id_progetto = ? AND owner_user_id = ?", (id_progetto, uid))
        if not c.fetchone():
            conn.close()
            return False
    curr_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        if stato_attuale_chiuso == 0:
            c.execute(
                "UPDATE progetti SET data_chiusura=?, completato=1 WHERE id_progetto=?",
                (curr_date, id_progetto),
            )
            c.execute(
                "UPDATE task SET data_completato=?, completato=1 WHERE id_progetto=? AND attivo=1",
                (curr_date, id_progetto),
            )
            # Quando un progetto viene chiuso, lo spostiamo in fondo alla lista.
            c.execute(
                """
                SELECT COALESCE(MAX(ordine_manuale), 0)
                FROM progetti
                WHERE attivo = 1 AND (archiviato = 0 OR archiviato IS NULL)
                """
            )
            ordine_fondo = int(c.fetchone()[0] or 0) + 1
            c.execute(
                "UPDATE progetti SET ordine_manuale = ? WHERE id_progetto = ?",
                (ordine_fondo, id_progetto),
            )
        else:
            c.execute(
                "UPDATE progetti SET data_chiusura=NULL, completato=0 WHERE id_progetto=?",
                (id_progetto,),
            )
            c.execute(
                "UPDATE task SET data_completato=NULL, completato=0 WHERE id_progetto=? AND attivo=1",
                (id_progetto,),
            )
        conn.commit()
        return True
    except Exception as e:
        print(f"Errore toggle chiusura progetto: {e}")
        conn.rollback()
        return False
    finally:
        conn.close()

#def modifica_progetto(id_prog, nome, note, stato_id):
#    conn = connetti()
#    c = conn.cursor()
#    # QUERY CORRETTA
#    c.execute("UPDATE progetti SET nome_progetto=?, note=?, id_stato=? WHERE id_progetto=?", 
#              (nome, note, stato_id, id_prog))
#    conn.commit()
#    conn.close()
#-----------------------------------------nuova veriosne
def modifica_progetto(id_proj, nome, note, id_stato, percentuale, id_r1, id_ru1, id_r2, id_ru2, data1_checkpoint, ticket_interno="", ticket_esterno=""):
    """Aggiorna nome, note, stato (Paese) e percentuale manuale del progetto."""
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    query = f"""
    UPDATE progetti SET 
            nome_progetto = ?,
            note = ?,
            id_stato = ?,
            percentuale_avanzamento = ?,
            id_resp1 = ?,
            id_ruolo_resp1 = ?,
            id_resp2 = ?,
            id_ruolo_resp2 = ?,
            data1_checkpoint = ?,
            ticket_interno = ?,
            ticket_esterno = ?
        WHERE id_progetto = ?{owner_filter}
    """
    try:
        conn = connetti()
        cursor = conn.cursor()
        params = (
            nome,
            note,
            id_stato,
            percentuale,
            id_r1,
            id_ru1,
            id_r2,
            id_ru2,
            data1_checkpoint,
            (ticket_interno or "").strip()[:20],
            (ticket_esterno or "").strip()[:20],
            id_proj,
        )
        if owner_filter:
            params = params + (uid,)
        cursor.execute(query, params)
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        print(f"Errore modifica progetto: {e}")
        return False

def ricalcola_avanzamento_progetto(id_proj):
    """Calcola la media dell'avanzamento dei task e aggiorna il progetto."""
    # 1. Calcola la media dai task attivi
    query_media = "SELECT AVG(percentuale_avanzamento) FROM task WHERE id_progetto = ? AND attivo = 1"
    
    # 2. Aggiorna il progetto
    query_update = "UPDATE progetti SET percentuale_avanzamento = ? WHERE id_progetto = ?"
    
    try:
        conn = connetti()
        cursor = conn.cursor()
        
        cursor.execute(query_media, (id_proj,))
        risultato = cursor.fetchone()
        
        # Se ci sono task, prendi la media, altrimenti 0
        nuova_perc = int(risultato[0]) if risultato and risultato[0] is not None else 0
        
        cursor.execute(query_update, (nuova_perc, id_proj))
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        print(f"Errore ricalcolo avanzamento: {e}")
        return False
    #----------------------------------
def elimina_logica_progetto(id_prog):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    
    try:
        # Calcolo data e ora attuali
        data_elim = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # 1. Elimina Progetto: Setta attivo=0 e scrive la data
        c.execute(
            f"UPDATE progetti SET attivo=0, data_eliminazione=? WHERE id_progetto=?{owner_filter}",
            (data_elim, id_prog) if not owner_filter else (data_elim, id_prog, uid),
        )
        
        # 2. Elimina Task a cascata: Setta attivo=0 e scrive la data per tutti i task di quel progetto
        c.execute(
            f"UPDATE task SET attivo=0, data_eliminazione=? WHERE id_progetto=?{owner_filter}",
            (data_elim, id_prog) if not owner_filter else (data_elim, id_prog, uid),
        )
        
        conn.commit()
    except Exception as e:
        print(f"Errore durante l'eliminazione del progetto: {e}")
        conn.rollback()
    finally:
        conn.close()

# --------------------------------------------------------
# GESTIONE TASK (Tabella SINGOLARE: task)
# --------------------------------------------------------
def leggi_tasks_di_progetto(id_progetto):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND t.owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    # QUERY CORRETTA: Tabella 'task', Join diretta su risorse
    sql = f"""
        SELECT 
            t.id_task, t.id_progetto, t.titolo, t.tipo_task, 
            t.percentuale_avanzamento, t.data_fine,
            r.nome || ' ' || r.cognome as nome_risorsa,
            t.data_inserimento,
            t.data_completato
        FROM task t
        LEFT JOIN risorse r ON t.id_risorsa = r.id_risorsa
        WHERE t.id_progetto = ? AND t.attivo = 1{owner_filter}
        ORDER BY t.data_inizio ASC, t.id_task ASC
    """
    c.execute(sql, (id_progetto,) if not owner_filter else (id_progetto, uid))
    items = c.fetchall()
    conn.close()
    return items


def leggi_tasks_con_progetti_attivi():
    """
    Elenca tutti i task attivi con nome progetto (LEFT JOIN).
    Output:
    id_task, id_progetto, nome_progetto, titolo, percentuale_avanzamento,
    data_inizio, data_fine, data_completato, nome_risorsa
    """
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND t.owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    sql = f"""
        SELECT
            t.id_task,
            t.id_progetto,
            COALESCE(p.nome_progetto, '') AS nome_progetto,
            t.titolo,
            t.percentuale_avanzamento,
            COALESCE(t.data_inizio, '') AS data_inizio,
            COALESCE(t.data_fine, '') AS data_fine,
            COALESCE(t.data_completato, '') AS data_completato,
            COALESCE(r.nome || ' ' || r.cognome, '') AS nome_risorsa
        FROM task t
        LEFT JOIN progetti p ON p.id_progetto = t.id_progetto
        LEFT JOIN risorse r ON r.id_risorsa = t.id_risorsa
        WHERE t.attivo = 1
          {owner_filter}
          AND (p.id_progetto IS NULL OR (p.attivo = 1 AND (p.archiviato = 0 OR p.archiviato IS NULL)))
        ORDER BY COALESCE(p.nome_progetto, ''), t.id_task DESC
    """
    c.execute(sql, (uid,) if owner_filter else None)
    rows = c.fetchall()
    conn.close()
    return rows


def aggiungi_nota_giornata(data_nota, testo, id_progetto=None, id_task=None):
    inizializza_db()
    testo = (testo or "").strip()
    if not testo:
        return False
    # La data nota e' sempre la data odierna (non editabile da UI).
    data_nota = datetime.now().strftime("%Y-%m-%d")
    ora_nota = datetime.now().strftime("%H:%M:%S")
    uid = _current_user_id()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        INSERT INTO note_giornata (data_nota, ora_nota, testo, id_progetto, id_task, attivo, owner_user_id)
        VALUES (?, ?, ?, ?, ?, 1, ?)
        """,
        (data_nota, ora_nota, testo, id_progetto, id_task, uid),
    )
    conn.commit()
    conn.close()
    return True


def leggi_note_giornata(data_nota=None, filtro_testo=""):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    where = ["n.attivo = 1"]
    params = []
    uid = _current_user_id()
    if uid is not None and not _is_admin():
        where.append("n.owner_user_id = ?")
        params.append(uid)
    if data_nota:
        where.append("n.data_nota = ?")
        params.append(data_nota)
    filtro = (filtro_testo or "").strip()
    if filtro:
        where.append("LOWER(n.testo) LIKE ?")
        params.append(f"%{filtro.lower()}%")

    sql = f"""
        SELECT
            n.id_nota,
            n.data_nota,
            COALESCE(n.ora_nota, '') AS ora_nota,
            n.testo,
            n.id_progetto,
            n.id_task,
            COALESCE(p.nome_progetto, '') AS nome_progetto,
            COALESCE(t.titolo, '') AS titolo_task
        FROM note_giornata n
        LEFT JOIN progetti p ON p.id_progetto = n.id_progetto
        LEFT JOIN task t ON t.id_task = n.id_task
        WHERE {' AND '.join(where)}
        ORDER BY n.data_nota DESC, n.ora_nota DESC, n.id_nota DESC
    """
    c.execute(sql, tuple(params))
    rows = c.fetchall()
    conn.close()
    return rows


def elimina_nota_giornata(id_nota):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    # Cancellazione definitiva richiesta (hard delete).
    c.execute(
        f"DELETE FROM note_giornata WHERE id_nota = ?{owner_filter}",
        (id_nota,) if not owner_filter else (id_nota, uid),
    )
    conn.commit()
    conn.close()


def crea_task_da_nota(id_nota, id_progetto):
    """
    Crea un task partendo dal testo di una nota giornata e collega la nota al task.
    Ritorna: (ok: bool, nuovo_id_task: int|None, msg: str)
    """
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    try:
        c.execute(
            f"SELECT testo FROM note_giornata WHERE id_nota = ? AND attivo = 1{owner_filter}",
            (id_nota,) if not owner_filter else (id_nota, uid),
        )
        row = c.fetchone()
        if not row:
            conn.close()
            return False, None, "Nota non trovata o non attiva."

        titolo = (row[0] or "").strip()
        if not titolo:
            conn.close()
            return False, None, "La nota Ã¨ vuota."

        data_ins = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        c.execute(
            """
            INSERT INTO task (
                id_progetto, titolo, data_inizio, data_fine,
                percentuale_avanzamento, tipo_task, id_stato,
                completato, data_inserimento, attivo, id_risorsa, id_ruolo, owner_user_id
            ) VALUES (?, ?, NULL, NULL, 0, 2, 1, 0, ?, 1, NULL, NULL, ?)
            RETURNING id_task
            """,
            (id_progetto, titolo, data_ins, uid),
        )
        new_task_id = c.fetchone()[0]

        c.execute(
            f"UPDATE note_giornata SET id_progetto = ?, id_task = ? WHERE id_nota = ?{owner_filter}",
            (id_progetto, new_task_id, id_nota) if not owner_filter else (id_progetto, new_task_id, id_nota, uid),
        )
        conn.commit()
        conn.close()
        return True, new_task_id, "Task creato dalla nota."
    except Exception as ex:
        conn.rollback()
        conn.close()
        return False, None, f"Errore creazione task da nota: {ex}"


def conta_allegati_task(id_task):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    c.execute(
        f"SELECT COUNT(*) FROM task_allegati WHERE id_task = ? AND attivo = 1{owner_filter}",
        (id_task,) if not owner_filter else (id_task, uid),
    )
    count = c.fetchone()[0]
    conn.close()
    return count


def leggi_allegati_task(id_task):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    c.execute(
        f"""
        SELECT id_allegato, nome_originale, percorso_relativo, data_inserimento
        FROM task_allegati
        WHERE id_task = ? AND attivo = 1{owner_filter}
        ORDER BY id_allegato DESC
        """,
        (id_task,) if not owner_filter else (id_task, uid),
    )
    rows = c.fetchall()
    conn.close()
    return rows


def aggiungi_allegato_task(id_task, source_file_path):
    if not source_file_path or not os.path.exists(source_file_path):
        return False, "File sorgente non trovato."

    try:
        inizializza_db()

        attachments_root = get_attachments_dir()
        task_dir = os.path.join(attachments_root, str(id_task))
        os.makedirs(task_dir, exist_ok=True)

        nome_originale = os.path.basename(source_file_path)
        nome_storage = f"{uuid.uuid4().hex[:10]}_{nome_originale}"
        target_abs = os.path.join(task_dir, nome_storage)
        shutil.copy2(source_file_path, target_abs)

        percorso_relativo = os.path.relpath(target_abs, get_project_root()).replace("\\", "/")
        data_ins = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        uid = _current_user_id()

        conn = connetti()
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO task_allegati
                (id_task, nome_originale, nome_file_storage, percorso_relativo, data_inserimento, attivo, owner_user_id)
            VALUES
                (?, ?, ?, ?, ?, 1, ?)
            """,
            (id_task, nome_originale, nome_storage, percorso_relativo, data_ins, uid),
        )
        conn.commit()
        conn.close()
        return True, "Allegato aggiunto."
    except Exception as e:
        return False, f"Errore aggiunta allegato: {e}"


def get_allegato_abs_path(id_allegato):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    c.execute(
        f"SELECT percorso_relativo, nome_file_storage FROM task_allegati WHERE id_allegato = ?{owner_filter}",
        (id_allegato,) if not owner_filter else (id_allegato, uid),
    )
    row = c.fetchone()
    conn.close()

    if not row:
        return None

    rel = row[0] or ""
    nome_storage = row[1] or ""

    # 1) Path assoluto giÃ  salvato nel DB.
    if os.path.isabs(rel) and os.path.exists(rel):
        return rel

    # 2) Prova path relativo su root correnti/legacy.
    candidate_roots = [
        get_project_root(),
        os.path.join(get_project_root(), "src"),
        os.path.join(os.getenv("APPDATA", ""), "Flet", "prg-flet", "flet"),
        os.path.join(os.getenv("APPDATA", ""), "Flet", "prg-flet", "flet", "app"),
    ]

    if rel:
        for root in candidate_roots:
            if not root:
                continue
            candidate = os.path.normpath(os.path.join(root, rel))
            if os.path.exists(candidate):
                return candidate

    # 3) Fallback: cerca il file storage in cartelle attachments note.
    if nome_storage:
        search_roots = [
            get_attachments_dir(),
            os.path.join(os.getenv("APPDATA", ""), "Flet", "prg-flet", "flet", "attachments"),
            os.path.join(os.getenv("APPDATA", ""), "Flet", "prg-flet", "flet", "app", "attachments"),
        ]
        for root in search_roots:
            if not root or not os.path.isdir(root):
                continue
            for dirpath, _, filenames in os.walk(root):
                if nome_storage in filenames:
                    return os.path.join(dirpath, nome_storage)

    return None


def leggi_allegati_abs_task(id_task):
    """Ritorna i percorsi assoluti degli allegati attivi di un task."""
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT percorso_relativo
        FROM task_allegati
        WHERE id_task = ? AND attivo = 1
        ORDER BY id_allegato ASC
        """,
        (id_task,),
    )
    rows = c.fetchall()
    conn.close()

    out = []
    for (rel,) in rows:
        if not rel:
            continue
        out.append(rel if os.path.isabs(rel) else os.path.join(get_project_root(), rel))
    return out


def leggi_allegati_abs_progetto(id_progetto):
    """Ritorna i percorsi assoluti degli allegati attivi dei task attivi di un progetto."""
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT ta.percorso_relativo
        FROM task_allegati ta
        JOIN task t ON ta.id_task = t.id_task
        WHERE ta.attivo = 1
          AND t.id_progetto = ?
          AND t.attivo = 1
        ORDER BY ta.id_allegato ASC
        """,
        (id_progetto,),
    )
    rows = c.fetchall()
    conn.close()

    out = []
    for (rel,) in rows:
        if not rel:
            continue
        out.append(rel if os.path.isabs(rel) else os.path.join(get_project_root(), rel))
    return out


def leggi_allegati_abs_risorsa(id_risorsa):
    """Ritorna i percorsi assoluti degli allegati attivi dei task attivi assegnati alla risorsa."""
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT ta.percorso_relativo
        FROM task_allegati ta
        JOIN task t ON ta.id_task = t.id_task
        LEFT JOIN progetti p ON t.id_progetto = p.id_progetto
        WHERE ta.attivo = 1
          AND t.attivo = 1
          AND t.id_risorsa = ?
          AND (p.id_progetto IS NULL OR (p.attivo = 1 AND (p.archiviato = 0 OR p.archiviato IS NULL)))
        ORDER BY ta.id_allegato ASC
        """,
        (id_risorsa,),
    )
    rows = c.fetchall()
    conn.close()

    out = []
    for (rel,) in rows:
        if not rel:
            continue
        out.append(rel if os.path.isabs(rel) else os.path.join(get_project_root(), rel))
    return out


def elimina_allegato_task(id_allegato):
    try:
        percorso_abs = get_allegato_abs_path(id_allegato)

        conn = connetti()
        c = conn.cursor()
        c.execute(
            "UPDATE task_allegati SET attivo = 0 WHERE id_allegato = ?",
            (id_allegato,),
        )
        conn.commit()
        conn.close()

        if percorso_abs and os.path.exists(percorso_abs):
            try:
                os.remove(percorso_abs)
            except Exception:
                pass

        return True, "Allegato rimosso."
    except Exception as e:
        return False, f"Errore rimozione allegato: {e}"

def leggi_dettaglio_task(id_task):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND t.owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    # QUERY CORRETTA: Legge id_risorsa direttamente da task
    sql = f"""
        SELECT 
            t.titolo, t.data_inizio, t.data_fine, t.percentuale_avanzamento, 
            t.tipo_task, t.id_stato, t.completato, t.data_inserimento,
            t.id_risorsa, t.id_ruolo,
            COALESCE(t.ticket_interno, '') AS ticket_interno,
            COALESCE(t.ticket_esterno, '') AS ticket_esterno
        FROM task t 
        WHERE t.id_task = ?{owner_filter}
        order by t.data_inserimento
    """
    c.execute(sql, (id_task,) if not owner_filter else (id_task, uid))
    res = c.fetchone()
    conn.close()
    return res

def salva_task_complesso(id_task, id_progetto, dati, assegnazione):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    
    # Mappatura dati dal dizionario UI ai campi DB
    titolo = dati.get("titolo")
    d_ini = dati.get("inizio")
    d_fine = dati.get("fine")
    perc = dati.get("perc")
    tipo = dati.get("tipo")
    stato = dati.get("stato")
    ticket_interno = (dati.get("ticket_interno") or "").strip()[:20]
    ticket_esterno = (dati.get("ticket_esterno") or "").strip()[:20]
    
    # Estrazione risorsa dalla tupla assegnazione (id_ris, id_ruolo)
    id_ris = None
    id_ruo = None
    if assegnazione:
        id_ris = assegnazione[0]
        if len(assegnazione) > 1: id_ruo = assegnazione[1]

    # Logica completamento
    completato = 1 if int(perc) == 100 else 0
    curr_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        if id_task:
            # UPDATE (Tabella task)
            sql = f"""
                UPDATE task SET 
                    titolo=?, data_inizio=?, data_fine=?, 
                    percentuale_avanzamento=?, tipo_task=?, id_stato=?,
                    completato = CASE WHEN ? = 100 THEN 1 ELSE 0 END,
                    id_risorsa = ?, id_ruolo = ?,
                    ticket_interno = ?, ticket_esterno = ?
                WHERE id_task=?{owner_filter}
            """
            params = (titolo, d_ini, d_fine, perc, tipo, stato, perc, id_ris, id_ruo, ticket_interno, ticket_esterno, id_task)
            if owner_filter:
                params = params + (uid,)
            c.execute(sql, params)
        else:
            # INSERT (Tabella task)
            sql = """
                INSERT INTO task (
                    id_progetto, titolo, data_inizio, data_fine, 
                    percentuale_avanzamento, tipo_task, id_stato, 
                    completato, data_inserimento, attivo, id_risorsa, id_ruolo, owner_user_id, ticket_interno, ticket_esterno
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?)
            """
            c.execute(sql, (id_progetto, titolo, d_ini, d_fine, perc, tipo, stato, completato, curr_date, id_ris, id_ruo, uid, ticket_interno, ticket_esterno))
        
        conn.commit()
        return True
    except Exception as e:
        print(f"Errore DB: {e}")
        return False
    finally:
        conn.close()

def toggle_completamento_task(id_task, stato_attuale_completato, tipo_task):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id=?" if (uid is not None and not _is_admin()) else ""
    curr_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    if stato_attuale_completato == 0:
        # Chiusura
        if tipo_task == 2: # Checklist
            sql = f"UPDATE task SET completato=1, percentuale_avanzamento=100, data_completato=? WHERE id_task=?{owner_filter}"
            c.execute(sql, (curr_date, id_task) if not owner_filter else (curr_date, id_task, uid))
        else:
            sql = f"UPDATE task SET completato=1, data_completato=? WHERE id_task=?{owner_filter}"
            c.execute(sql, (curr_date, id_task) if not owner_filter else (curr_date, id_task, uid))
    else:
        # Riapertura
        sql = f"UPDATE task SET completato=0, percentuale_avanzamento=0, data_completato=NULL WHERE id_task=?{owner_filter}"
        c.execute(sql, (id_task,) if not owner_filter else (id_task, uid))
        
    conn.commit()
    conn.close()

#def elimina_logica_task(id_task):
#    conn = connetti()
#    c = conn.cursor()
#    c.execute("UPDATE task SET attivo=0 WHERE id_task=?", (id_task,))
#    conn.commit()
#    conn.close()
    
def elimina_logica_task(id_task):
    conn = connetti()
    cursor = conn.cursor()
    
    try:
        # Prendi la data e ora attuali
        data_elim = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Aggiorna sia lo stato attivo che la data_eliminazione
        uid = _current_user_id()
        owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
        query = f"UPDATE task SET attivo = 0, data_eliminazione = ? WHERE id_task = ?{owner_filter}"
        
        cursor.execute(query, (data_elim, id_task) if not owner_filter else (data_elim, id_task, uid))
        conn.commit()
        return True
    except Exception as e:
        print(f"Errore eliminazione task: {e}")
        return False
    finally:
        conn.close()

# --------------------------------------------------------
# RISORSE E RUOLI (Per le dropdown)
# --------------------------------------------------------
def leggi_stati():
    conn = connetti()
    c = conn.cursor()
   # Unisce un record fittizio (0, '') ai dati reali
    query = """
        SELECT id_stato, nome_stato FROM tab_stati 
        ORDER BY 2
    """
    c.execute(query)
    items = c.fetchall()
    conn.close()
    return items

def leggi_risorse_attive():
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
     # Nota: servono 3 colonne perchÃ© la tabella risorse ne restituisce 3
    query = """
        SELECT id_risorsa, nome, cognome, email FROM risorse WHERE attivo = 1
        ORDER BY 3, 2
    """
    c.execute(query)
    items = c.fetchall()
    conn.close()
    return items

def aggiungi_risorsa(nome, cognome, email):
    conn = connetti()
    c = conn.cursor()
    c.execute("INSERT INTO risorse (nome, cognome, email, attivo) VALUES (?, ?, ?, 1)", (nome, cognome, email))
    conn.commit()
    conn.close()

def modifica_risorsa(id_ris, nome, cognome, email):
    conn = connetti()
    c = conn.cursor()
    c.execute("UPDATE risorse SET nome=?, cognome=?, email=? WHERE id_risorsa=?", (nome, cognome, email, id_ris))
    conn.commit()
    conn.close()

def elimina_logica_risorsa(id_ris):
    conn = connetti()
    c = conn.cursor()
    c.execute("UPDATE risorse SET attivo=0 WHERE id_risorsa=?", (id_ris,))
    conn.commit()
    conn.close()

def leggi_ruoli_attivi():
    conn = connetti()
    c = conn.cursor()
    # Unisce record fittizio (0, '') ai dati reali
    query = """
        SELECT id_ruolo, nome_ruolo FROM ruoli WHERE attivo = 1
        ORDER BY 2
    """
    c.execute(query)
    items = c.fetchall()
    conn.close()
    return items

def aggiungi_ruolo(nome):
    conn = connetti()
    c = conn.cursor()
    c.execute("INSERT INTO ruoli (nome_ruolo, attivo) VALUES (?, 1)", (nome,))
    conn.commit()
    conn.close()

def modifica_ruolo(id_ruolo, nuovo_nome):
    conn = connetti()
    c = conn.cursor()
    c.execute("UPDATE ruoli SET nome_ruolo = ? WHERE id_ruolo = ?", (nuovo_nome, id_ruolo))
    conn.commit()
    conn.close()

def elimina_logica_ruolo(id_ruolo):
    conn = connetti()
    c = conn.cursor()
    c.execute("UPDATE ruoli SET attivo = 0 WHERE id_ruolo = ?", (id_ruolo,))
    conn.commit()
    conn.close()

def archivia_progetto_db(id_prog):
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    try:
        # Usa il formato standard ISO per le date
        data_arch = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # 1. Archivia il Progetto
        c.execute(
            """
            UPDATE progetti 
            SET archiviato = 1, data_archiviazione = ? 
            WHERE id_progetto = ?
            """
            + owner_filter,
            (data_arch, id_prog) if not owner_filter else (data_arch, id_prog, uid),
        )
        
        # 2. Archivia a cascata i Task del progetto
        c.execute(
            """
            UPDATE task 
            SET archiviato = 1, data_archiviazione = ? 
            WHERE id_progetto = ?
            """
            + owner_filter,
            (data_arch, id_prog) if not owner_filter else (data_arch, id_prog, uid),
        )
        
        conn.commit()
        return True
    except Exception as e:
        print(f"Errore archiviazione: {e}")
        return False
    finally:
        conn.close()
# --- INSERIRE IN src/db_handler_progetti.py ---

def leggi_progetti_archiviati():
    """Legge solo i progetti archiviati (attivi=1 MA archiviato=1)"""
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    
    query = f"""
        SELECT id_progetto, nome_progetto, note, id_stato, percentuale_avanzamento 
        FROM progetti 
        WHERE attivo = 1 AND archiviato = 1{owner_filter}
        ORDER BY data_archiviazione DESC, id_progetto DESC
    """
    
    try:
        c.execute(query, (uid,) if owner_filter else None)
        dati = c.fetchall()
        return dati
    except Exception as e:
        print(f"Errore lettura archivio: {e}")
        return []
    finally:
        conn.close()

def ripristina_progetto_db(id_prog):
    """Riporta un progetto e i suoi task in 'Gestione' (archiviato = 0)"""
    conn = connetti()
    c = conn.cursor()
    uid = _current_user_id()
    owner_filter = " AND owner_user_id = ?" if (uid is not None and not _is_admin()) else ""
    try:
        # 1. Ripristina Progetto (Pulisce anche la data archiviazione per ordine)
        c.execute(
            """
            UPDATE progetti 
            SET archiviato = 0, data_archiviazione = NULL 
            WHERE id_progetto = ?
            """
            + owner_filter,
            (id_prog,) if not owner_filter else (id_prog, uid),
        )
        
        # 2. Ripristina Task a cascata
        c.execute(
            """
            UPDATE task 
            SET archiviato = 0, data_archiviazione = NULL 
            WHERE id_progetto = ?
            """
            + owner_filter,
            (id_prog,) if not owner_filter else (id_prog, uid),
        )
        
        conn.commit()
        return True
    except Exception as e:
        print(f"Errore ripristino progetto: {e}")
        return False
    finally:
        conn.close()
        
def leggi_dati_stampa_lista():
    """
    Recupera dati lista progetti + Conteggio Task Attivi + Data Chiusura Progetto
    """
    conn = connetti()
    c = conn.cursor()
    owner_filter, owner_params = owner_filter_sql("p")
    
    # MODIFICA: 
    # 1. num_tasks: Conta SOLO i task con attivo=1 (esclude cancellati/archiviati)
    # 2. data_chiusura: Legge direttamente dal progetto (p.data_chiusura)
    query = f"""
        SELECT 
            p.nome_progetto,
            COALESCE(s.nome_stato, '') as stato,
            p.percentuale_avanzamento,
            COALESCE(r1.cognome || ' ' || r1.nome, '') as resp1,
            COALESCE(r2.cognome || ' ' || r2.nome, '') as resp2,
            (
                SELECT COUNT(*)
                FROM task t
                WHERE t.id_progetto = p.id_progetto
                  AND t.attivo = 1
                  {("AND t.owner_user_id = ?" if owner_filter else "")}
            ) as num_tasks,
            p.data_chiusura,
            COALESCE(p.ticket_interno, '') AS ticket_interno,
            COALESCE(p.ticket_esterno, '') AS ticket_esterno
        FROM progetti p
        LEFT JOIN tab_stati s ON p.id_stato = s.id_stato
        LEFT JOIN risorse r1 ON p.id_resp1 = r1.id_risorsa
        LEFT JOIN risorse r2 ON p.id_resp2 = r2.id_risorsa
        WHERE p.attivo = 1 
          AND (p.archiviato = 0 OR p.archiviato IS NULL)
          {owner_filter}
        ORDER BY p.nome_progetto ASC
    """
    if owner_filter:
        params = owner_params + owner_params
    else:
        params = None
    c.execute(query, params)
    dati = c.fetchall()
    conn.close()
    return dati


def leggi_attivita_scadute():
    """
    Elenca Attività Scadute:
    - Progetti con data1_checkpoint < data odierna.
    - Task con data_fine < data odierna e non completati.
    Output tuple:
    (tipo, id_progetto, id_task, descrizione, data_scadenza)
    """
    inizializza_db()
    oggi = datetime.now().strftime("%Y-%m-%d")
    conn = connetti()
    c = conn.cursor()
    owner_filter_p, owner_params_p = owner_filter_sql("p")
    owner_filter_t, owner_params_t = owner_filter_sql("t")

    sql = f"""
        SELECT
            'PROGETTO' AS tipo,
            p.id_progetto AS id_progetto,
            NULL AS id_task,
            p.nome_progetto AS descrizione,
            SUBSTR(COALESCE(p.data1_checkpoint, ''), 1, 10) AS data_scadenza
        FROM progetti p
        WHERE p.attivo = 1
          AND (p.archiviato = 0 OR p.archiviato IS NULL)
          {owner_filter_p}
          AND TRIM(COALESCE(p.data1_checkpoint, '')) <> ''
          AND to_date(SUBSTR(p.data1_checkpoint, 1, 10), 'YYYY-MM-DD') < %s::date

        UNION ALL

        SELECT
            'TASK' AS tipo,
            t.id_progetto AS id_progetto,
            t.id_task AS id_task,
            t.titolo AS descrizione,
            SUBSTR(COALESCE(t.data_fine, ''), 1, 10) AS data_scadenza
        FROM task t
        LEFT JOIN progetti p ON p.id_progetto = t.id_progetto
        WHERE t.attivo = 1
          {owner_filter_t}
          AND COALESCE(t.completato, 0) = 0
          AND TRIM(COALESCE(t.data_fine, '')) <> ''
          AND to_date(SUBSTR(t.data_fine, 1, 10), 'YYYY-MM-DD') < %s::date
          AND (p.id_progetto IS NULL OR (p.attivo = 1 AND (p.archiviato = 0 OR p.archiviato IS NULL)))

        ORDER BY data_scadenza ASC, tipo DESC
    """
    params = []
    if owner_filter_p:
        params.extend(owner_params_p)
    params.append(oggi)
    if owner_filter_t:
        params.extend(owner_params_t)
    params.append(oggi)
    c.execute(sql, tuple(params))
    rows = c.fetchall()
    conn.close()
    return rows


# --------------------------------------------------------
# AUTENTICAZIONE UTENTI
# --------------------------------------------------------
def _associa_ruolo_utente(c, id_utente: int, ruolo_codice: str):
    role = (ruolo_codice or "USER").strip().upper()
    if role not in ("ADMIN", "USER"):
        role = "USER"
    c.execute("DELETE FROM utenti_ruoli WHERE id_utente = ?", (id_utente,))
    c.execute(
        """
        INSERT INTO utenti_ruoli (id_utente, id_ruolo)
        SELECT ?, id_ruolo
        FROM ruoli_app
        WHERE codice = ?
        ON CONFLICT (id_utente, id_ruolo) DO NOTHING
        """,
        (id_utente, role),
    )


def _ensure_ruolo_link(c, id_utente: int, legacy_role: str):
    c.execute("SELECT 1 FROM utenti_ruoli WHERE id_utente = ? LIMIT 1", (id_utente,))
    if c.fetchone() is None:
        _associa_ruolo_utente(c, id_utente, legacy_role)


def ruoli_utente(id_utente: int):
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT ra.codice
        FROM utenti_ruoli ur
        JOIN ruoli_app ra ON ra.id_ruolo = ur.id_ruolo
        WHERE ur.id_utente = ?
        ORDER BY ra.codice
        """,
        (id_utente,),
    )
    rows = [r[0] for r in c.fetchall()]
    conn.close()
    return rows


def permessi_utente(id_utente: int):
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT DISTINCT p.codice
        FROM utenti_ruoli ur
        JOIN ruoli_permessi rp ON rp.id_ruolo = ur.id_ruolo
        JOIN permessi p ON p.id_permesso = rp.id_permesso
        WHERE ur.id_utente = ?
        ORDER BY p.codice
        """,
        (id_utente,),
    )
    rows = [r[0] for r in c.fetchall()]
    conn.close()
    return rows


def has_permission(id_utente: int, codice_permesso: str) -> bool:
    if not id_utente or not codice_permesso:
        return False
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT 1
        FROM utenti_ruoli ur
        JOIN ruoli_permessi rp ON rp.id_ruolo = ur.id_ruolo
        JOIN permessi p ON p.id_permesso = rp.id_permesso
        WHERE ur.id_utente = ?
          AND p.codice = ?
        LIMIT 1
        """,
        (id_utente, codice_permesso),
    )
    ok = c.fetchone() is not None
    conn.close()
    return ok


def applicazioni_visibili_utente(id_utente: int):
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT DISTINCT a.codice, a.nome, a.route
        FROM applicazioni a
        JOIN applicazioni_permessi ap ON ap.id_app = a.id_app
        JOIN ruoli_permessi rp ON rp.id_permesso = ap.id_permesso
        JOIN utenti_ruoli ur ON ur.id_ruolo = rp.id_ruolo
        WHERE a.attiva = TRUE
          AND ur.id_utente = ?
        ORDER BY a.nome ASC
        """,
        (id_utente,),
    )
    rows = c.fetchall()
    conn.close()
    return [{"codice": r[0], "nome": r[1], "route": r[2]} for r in rows]


def hash_password(password: str) -> str:
    """
    Hash PBKDF2-SHA256 in formato:
    pbkdf2_sha256$<iter>$<salt_hex>$<hash_hex>
    """
    raw = (password or "").encode("utf-8")
    iterations = 200000
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", raw, salt, iterations)
    return f"pbkdf2_sha256${iterations}${salt.hex()}${digest.hex()}"


def verifica_password(password: str, stored_hash: str) -> bool:
    """
    Verifica hash PBKDF2.
    CompatibilitÃ  legacy: se hash non in formato noto, confronto diretto.
    """
    if not stored_hash:
        return False
    if stored_hash.startswith("pbkdf2_sha256$"):
        try:
            _, it_s, salt_hex, digest_hex = stored_hash.split("$", 3)
            iterations = int(it_s)
            salt = bytes.fromhex(salt_hex)
            expected = bytes.fromhex(digest_hex)
            current = hashlib.pbkdf2_hmac(
                "sha256", (password or "").encode("utf-8"), salt, iterations
            )
            return hmac.compare_digest(current, expected)
        except Exception:
            return False
    return (password or "") == stored_hash


def autentica_utente(username: str, password: str):
    inizializza_db()
    uname = (username or "").strip()
    if not uname or not password:
        return None

    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT id_utente, username, password_hash, ruolo, attivo
        FROM utenti
        WHERE LOWER(username) = LOWER(?)
        LIMIT 1
        """,
        (uname,),
    )
    row = c.fetchone()
    if not row:
        conn.close()
        return None
    if not bool(row[4]):
        conn.close()
        return None
    if not verifica_password(password, row[2]):
        conn.close()
        return None
    _ensure_ruolo_link(c, row[0], row[3])
    conn.commit()
    conn.close()

    ruoli = ruoli_utente(row[0])
    permessi = permessi_utente(row[0])
    ruolo_effettivo = "ADMIN" if "ADMIN" in ruoli else (row[3] or "USER")
    return {
        "id_utente": row[0],
        "username": row[1],
        "ruolo": ruolo_effettivo,
        "ruoli": ruoli,
        "permessi": permessi,
        "applicazioni": applicazioni_visibili_utente(row[0]),
    }


def crea_o_aggiorna_utente(username: str, password: str, ruolo: str = "USER", attivo: int = 1, nome: str = "", cognome: str = "", email: str = ""):
    inizializza_db()
    uname = (username or "").strip()
    role = (ruolo or "USER").strip().upper()
    if role not in ("ADMIN", "USER"):
        role = "USER"
    if not uname or not password:
        return False, "Username e password obbligatori."

    pw_hash = hash_password(password)
    conn = connetti()
    c = conn.cursor()
    try:
        c.execute(
            """
            INSERT INTO utenti (username, password_hash, nome, cognome, email, ruolo, attivo)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (username)
            DO UPDATE SET
                password_hash = EXCLUDED.password_hash,
                nome = EXCLUDED.nome,
                cognome = EXCLUDED.cognome,
                email = EXCLUDED.email,
                ruolo = EXCLUDED.ruolo,
                attivo = EXCLUDED.attivo
            """,
            (uname, pw_hash, (nome or "").strip(), (cognome or "").strip(), (email or "").strip(), role, bool(attivo)),
        )
        c.execute("SELECT id_utente FROM utenti WHERE LOWER(username)=LOWER(?) LIMIT 1", (uname,))
        row = c.fetchone()
        if row:
            _associa_ruolo_utente(c, row[0], role)
        conn.commit()
        return True, "Utente salvato."
    except Exception as ex:
        conn.rollback()
        return False, f"Errore salvataggio utente: {ex}"
    finally:
        conn.close()


def leggi_utenti():
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT id_utente, username, COALESCE(nome, ''), COALESCE(cognome, ''), COALESCE(email, ''), ruolo, attivo, created_at
        FROM utenti
        ORDER BY username ASC
        """
    )
    rows = c.fetchall()
    conn.close()
    return rows


def imposta_ruolo_utente(id_utente: int, ruolo: str):
    role = (ruolo or "USER").strip().upper()
    if role not in ("ADMIN", "USER"):
        role = "USER"
    conn = connetti()
    c = conn.cursor()
    c.execute(
        "UPDATE utenti SET ruolo = ? WHERE id_utente = ?",
        (role, id_utente),
    )
    _associa_ruolo_utente(c, id_utente, role)
    conn.commit()
    conn.close()


def imposta_attivo_utente(id_utente: int, attivo: int):
    conn = connetti()
    c = conn.cursor()
    c.execute(
        "UPDATE utenti SET attivo = ? WHERE id_utente = ?",
        (bool(attivo), id_utente),
    )
    conn.commit()
    conn.close()


def reset_password_utente(id_utente: int, nuova_password: str):
    if not nuova_password:
        return False, "Password vuota."
    conn = connetti()
    c = conn.cursor()
    try:
        c.execute(
            "UPDATE utenti SET password_hash = ? WHERE id_utente = ?",
            (hash_password(nuova_password), id_utente),
        )
        conn.commit()
        return True, "Password aggiornata."
    except Exception as ex:
        conn.rollback()
        return False, f"Errore reset password: {ex}"
    finally:
        conn.close()



def leggi_categorie_modulo():
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT codice, descrizione
        FROM categorie_modulo
        ORDER BY codice ASC
        """
    )
    rows = c.fetchall()
    conn.close()
    return [(str(r[0] or ''), str(r[1] or '')) for r in rows]


def leggi_moduli_disponibili():
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT id_app, codice, nome, route, attiva,
               COALESCE(descrizione, ''),
               COALESCE(icona, ''),
               COALESCE(categoria, ''),
               COALESCE(ordine_menu, 1000),
               COALESCE(visibile_menu, TRUE)
        FROM applicazioni
        ORDER BY COALESCE(ordine_menu, 1000) ASC, nome ASC
        """
    )
    rows = c.fetchall()
    conn.close()
    return rows


def leggi_moduli_utente(id_utente: int):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    c.execute(
        """
        SELECT a.codice
        FROM utenti_applicazioni ua
        JOIN applicazioni a ON a.id_app = ua.id_app
        WHERE ua.id_utente = ?
          AND ua.attivo = TRUE
        ORDER BY a.codice ASC
        """,
        (id_utente,),
    )
    rows = [r[0] for r in c.fetchall()]
    conn.close()
    return rows


def imposta_moduli_utente(id_utente: int, codici_modulo: list[str]):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    try:
        normalized = sorted({(x or "").strip().upper() for x in (codici_modulo or []) if (x or "").strip()})

        c.execute("SELECT id_utente FROM utenti WHERE id_utente = ? LIMIT 1", (id_utente,))
        if c.fetchone() is None:
            conn.rollback()
            return False, "Utente non trovato"

        c.execute("SELECT codice, id_app FROM applicazioni")
        m = {str(r[0]).upper(): int(r[1]) for r in c.fetchall()}
        unknown = [x for x in normalized if x not in m]
        if unknown:
            conn.rollback()
            return False, f"Codici modulo non validi: {', '.join(unknown)}"

        c.execute("DELETE FROM utenti_applicazioni WHERE id_utente = ?", (id_utente,))
        for code in normalized:
            c.execute(
                """
                INSERT INTO utenti_applicazioni (id_utente, id_app, attivo)
                VALUES (?, ?, TRUE)
                ON CONFLICT (id_utente, id_app)
                DO UPDATE SET attivo = EXCLUDED.attivo
                """,
                (id_utente, m[code]),
            )

        conn.commit()
        return True, "Abilitazioni aggiornate"
    except Exception as ex:
        conn.rollback()
        return False, f"Errore salvataggio abilitazioni: {ex}"
    finally:
        conn.close()

def crea_app_modulo(codice: str, nome: str, route: str, descrizione: str = "", icona: str = "", categoria: str = "", ordine_menu: int = 1000, attiva: bool = True, visibile_menu: bool = True):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    try:
        cod = (codice or "").strip().upper()
        n = (nome or "").strip()
        r = (route or "").strip()
        if not r.startswith("/"):
            r = "/" + r
        if not cod or not n or not r:
            conn.rollback()
            return False, "Codice, nome e route sono obbligatori"

        cat = (categoria or "").strip().upper()
        if not cat:
            conn.rollback()
            return False, "Categoria modulo obbligatoria"
        if len(cat) > 5:
            conn.rollback()
            return False, "Categoria modulo non valida (max 5 caratteri)"
        c.execute("SELECT COUNT(*) FROM categorie_modulo WHERE codice = ?", (cat,))
        if int(c.fetchone()[0] or 0) == 0:
            conn.rollback()
            return False, f"Categoria modulo non trovata: {cat}"

        c.execute("SELECT COUNT(*) FROM applicazioni WHERE codice = ?", (cod,))
        if int(c.fetchone()[0] or 0) > 0:
            conn.rollback()
            return False, f"Codice gia presente: {cod}"

        c.execute("SELECT COUNT(*) FROM applicazioni WHERE route = ?", (r,))
        if int(c.fetchone()[0] or 0) > 0:
            conn.rollback()
            return False, f"Route gia presente: {r}"

        c.execute(
            """
            INSERT INTO applicazioni (codice, nome, route, attiva, descrizione, icona, categoria, ordine_menu, visibile_menu)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (cod, n, r, bool(attiva), (descrizione or "").strip() or None, (icona or "").strip() or None,
             cat, int(ordine_menu or 1000), bool(visibile_menu)),
        )
        conn.commit()
        return True, "Applicazione creata"
    except Exception as ex:
        conn.rollback()
        return False, f"Errore creazione app: {ex}"
    finally:
        conn.close()


def aggiorna_app_modulo(id_app: int, codice: str, nome: str, route: str, descrizione: str = "", icona: str = "", categoria: str = "", ordine_menu: int = 1000, attiva: bool = True, visibile_menu: bool = True):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    try:
        cod = (codice or "").strip().upper()
        n = (nome or "").strip()
        r = (route or "").strip()
        if not r.startswith("/"):
            r = "/" + r
        if not cod or not n or not r:
            conn.rollback()
            return False, "Codice, nome e route sono obbligatori"

        cat = (categoria or "").strip().upper()
        if not cat:
            conn.rollback()
            return False, "Categoria modulo obbligatoria"
        if len(cat) > 5:
            conn.rollback()
            return False, "Categoria modulo non valida (max 5 caratteri)"
        c.execute("SELECT COUNT(*) FROM categorie_modulo WHERE codice = ?", (cat,))
        if int(c.fetchone()[0] or 0) == 0:
            conn.rollback()
            return False, f"Categoria modulo non trovata: {cat}"

        c.execute("SELECT COUNT(*) FROM applicazioni WHERE id_app = ?", (id_app,))
        if int(c.fetchone()[0] or 0) == 0:
            conn.rollback()
            return False, "Applicazione non trovata"

        c.execute("SELECT COUNT(*) FROM applicazioni WHERE codice = ? AND id_app <> ?", (cod, id_app))
        if int(c.fetchone()[0] or 0) > 0:
            conn.rollback()
            return False, f"Codice gia presente: {cod}"

        c.execute("SELECT COUNT(*) FROM applicazioni WHERE route = ? AND id_app <> ?", (r, id_app))
        if int(c.fetchone()[0] or 0) > 0:
            conn.rollback()
            return False, f"Route gia presente: {r}"

        c.execute(
            """
            UPDATE applicazioni
            SET codice = ?, nome = ?, route = ?, attiva = ?,
                descrizione = ?, icona = ?, categoria = ?, ordine_menu = ?, visibile_menu = ?
            WHERE id_app = ?
            """,
            (cod, n, r, bool(attiva), (descrizione or "").strip() or None, (icona or "").strip() or None,
             cat, int(ordine_menu or 1000), bool(visibile_menu), id_app),
        )
        conn.commit()
        return True, "Applicazione aggiornata"
    except Exception as ex:
        conn.rollback()
        return False, f"Errore aggiornamento app: {ex}"
    finally:
        conn.close()


def imposta_attiva_app_modulo(id_app: int, attiva: bool):
    inizializza_db()
    conn = connetti()
    c = conn.cursor()
    try:
        c.execute("UPDATE applicazioni SET attiva = ? WHERE id_app = ?", (bool(attiva), id_app))
        if c.rowcount == 0:
            conn.rollback()
            return False, "Applicazione non trovata"
        conn.commit()
        return True, "Stato applicazione aggiornato"
    except Exception as ex:
        conn.rollback()
        return False, f"Errore aggiornamento stato app: {ex}"
    finally:
        conn.close()
