-- RBAC setup base per organizer_proj

CREATE TABLE IF NOT EXISTS ruoli_app (
  id_ruolo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codice VARCHAR(50) NOT NULL UNIQUE,
  descrizione VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS permessi (
  id_permesso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codice VARCHAR(80) NOT NULL UNIQUE,
  descrizione VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS utenti_ruoli (
  id_utente INTEGER NOT NULL,
  id_ruolo INTEGER NOT NULL,
  PRIMARY KEY (id_utente, id_ruolo),
  FOREIGN KEY (id_utente) REFERENCES utenti(id_utente) ON DELETE CASCADE,
  FOREIGN KEY (id_ruolo) REFERENCES ruoli_app(id_ruolo) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ruoli_permessi (
  id_ruolo INTEGER NOT NULL,
  id_permesso INTEGER NOT NULL,
  PRIMARY KEY (id_ruolo, id_permesso),
  FOREIGN KEY (id_ruolo) REFERENCES ruoli_app(id_ruolo) ON DELETE CASCADE,
  FOREIGN KEY (id_permesso) REFERENCES permessi(id_permesso) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS applicazioni (
  id_app INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codice VARCHAR(80) NOT NULL UNIQUE,
  nome VARCHAR(120) NOT NULL,
  route VARCHAR(120) NOT NULL,
  attiva BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS applicazioni_permessi (
  id_app INTEGER NOT NULL,
  id_permesso INTEGER NOT NULL,
  PRIMARY KEY (id_app, id_permesso),
  FOREIGN KEY (id_app) REFERENCES applicazioni(id_app) ON DELETE CASCADE,
  FOREIGN KEY (id_permesso) REFERENCES permessi(id_permesso) ON DELETE CASCADE
);

INSERT INTO ruoli_app (codice, descrizione) VALUES
  ('ADMIN', 'Amministratore'),
  ('USER', 'Utente standard')
ON CONFLICT (codice) DO NOTHING;

INSERT INTO permessi (codice, descrizione) VALUES
  ('APP_GESTIONE_OPEN', 'Accesso modulo Gestione Progetti'),
  ('APP_AS400_OPEN', 'Accesso modulo AS400')
ON CONFLICT (codice) DO NOTHING;

INSERT INTO applicazioni (codice, nome, route, attiva) VALUES
  ('GESTIONE', 'Gestione Progetti', '/gestione', TRUE),
  ('AS400', 'AS400', '/as400', TRUE)
ON CONFLICT (codice)
DO UPDATE SET
  nome = EXCLUDED.nome,
  route = EXCLUDED.route,
  attiva = EXCLUDED.attiva;

INSERT INTO ruoli_permessi (id_ruolo, id_permesso)
SELECT r.id_ruolo, p.id_permesso
FROM ruoli_app r
CROSS JOIN permessi p
WHERE r.codice = 'ADMIN'
ON CONFLICT (id_ruolo, id_permesso) DO NOTHING;

INSERT INTO ruoli_permessi (id_ruolo, id_permesso)
SELECT r.id_ruolo, p.id_permesso
FROM ruoli_app r
JOIN permessi p ON p.codice = 'APP_GESTIONE_OPEN'
WHERE r.codice = 'USER'
ON CONFLICT (id_ruolo, id_permesso) DO NOTHING;

INSERT INTO applicazioni_permessi (id_app, id_permesso)
SELECT a.id_app, p.id_permesso
FROM applicazioni a
JOIN permessi p ON p.codice = 'APP_GESTIONE_OPEN'
WHERE a.codice = 'GESTIONE'
ON CONFLICT (id_app, id_permesso) DO NOTHING;

INSERT INTO applicazioni_permessi (id_app, id_permesso)
SELECT a.id_app, p.id_permesso
FROM applicazioni a
JOIN permessi p ON p.codice = 'APP_AS400_OPEN'
WHERE a.codice = 'AS400'
ON CONFLICT (id_app, id_permesso) DO NOTHING;
